# Generated by Django 5.0.7 on 2024-09-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_animal', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=20)),
                ('raca', models.CharField(max_length=50)),
                ('idade', models.IntegerField()),
                ('especie', models.CharField(max_length=50)),
                ('peso', models.CharField(max_length=10)),
                ('rfid', models.CharField(max_length=50)),
                ('castrado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senha_funcionario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tutor', models.CharField(max_length=100)),
                ('numero_cad', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=11)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
    ]
