# Generated by Django 4.2.16 on 2024-10-17 22:48

import CBEA_APP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendar_consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tutor', models.CharField(max_length=100)),
                ('nome_animal', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('codigo_animal', models.AutoField(primary_key=True, serialize=False)),
                ('nome_animal', models.CharField(max_length=100, validators=[CBEA_APP.models.validate_nome_animal])),
                ('raca', models.CharField(max_length=50, validators=[CBEA_APP.models.validate_raca])),
                ('idade', models.IntegerField(validators=[CBEA_APP.models.validate_idade])),
                ('especie', models.CharField(max_length=50, validators=[CBEA_APP.models.validate_especie])),
                ('peso', models.CharField(max_length=10, validators=[CBEA_APP.models.validate_peso])),
                ('rfid', models.CharField(max_length=50, validators=[CBEA_APP.models.validate_rfid])),
                ('castrado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senha_funcionario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tutor', models.CharField(max_length=100)),
                ('numero_cad', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=11)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
    ]
