# Generated by Django 4.2.16 on 2024-10-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBEA_APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='id',
        ),
        migrations.AddField(
            model_name='tutor',
            name='codigo_tutor',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
